## 1 异常

> 将问题检测和问题处理相分离
>
> 异常机制和函数机制互不干涉,但是捕捉方式是通过严格类型匹配

- 异常的基本语法
  - 将可能抛出异常的程序段放到try块之中
  - 若有异常则通过throw操作创建一个异常对象并抛出
  - catch子句会根据出现的先后顺序被检查，匹配的catch语句捕获并处理异常(或继续抛出异常)
  - 如果在try段执行期间没有引起异常，那么跟在try后面的catch字句就不会执行
  - catch(类型) 如果想捕获其他类型的异常可使用catch(…)
  - 处理不了的异常，可以在catch的最后一个分支，使用throw，向上抛
  - 异常必须有函数进行处理，如果都不去处理，程序自动调用terminate函数中断掉

- 系统标准异常
  - 引入头文件：#include <stdexcept>
  - 抛出越界异常：throw out_of_range(“…”)
  - 获取错误信息：catch( exception & e )

> 栈解旋
>
> - 异常被抛出后，从进入try块起，到异常被抛掷前，这期间在栈上构造的所有对象，都会被自动析构
>   	析构的顺序与构造的顺序相反，这一过程称为栈的解旋(unwinding)

## 2 异常接口声明

> 如果一个函数抛出了它的异常接口声明所不允许抛出的异常，unexcepted函数会被调用，该函数默认行为调用terminate函数中断程序

- 可以在函数声明中列出可能抛出异常的所有类型

  - `void func() throw(A,B,C);`

    函数func能够且只能抛出类型A,B,C及其子类型的异常

- 如果在函数声明中没有包含异常接口声明，则此函数可以抛任何类型的异常

  - `void func()`

- 不抛任何类型异常的函数可声明为

  - `void func() throw()`

## 3 异常变量的生命周期

- 抛出的是 `throw MyException();`
  - `catch (MyException e)`	--调用拷贝构造函数，效率低
- 抛出的是 `throw MyException(); `
  - `catch (MyException &e)`	--只调用默认构造函数，效率高
- 抛出的是 `throw &MyException();`
  - `catch (MyException *e)`	--对象会提前释放掉，不能在非法操作
- 抛出的是 `new MyException(); `
  - `catch (MyException *e)`	--只调用默认构造函数，自己要管理释放



